export const GET_DATA_REQUEST="GET_DATA_REQUEST"
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS"
export const GET_DATA_FAILURE="GET_DATA_FAILURE"

export const BOOK_MOVIE_REQUEST="BOOK_MOVIE_REQUEST"
export const BOOK_MOVIE_SUCCESS="BOOK_MOVIE_SUCCESS"
export const BOOK_MOVIE_FAILURE="BOOK_MOVIE_FAILURE"